# Generated by Django 5.0.7 on 2024-07-24 22:42
"""
Migration script for creating the PizzaOrder model.
"""
# pylint: disable=C0103

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration class for creating the PizzaOrder model.
    """

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('pizza_type', models.CharField(
                    choices=[
                        ('margherita', 'Margherita'),
                        ('pepperoni', 'Pepperoni'),
                        ('vegetarian', 'Vegetarian')
                    ],
                    max_length=50
                )),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
